import json
import csv
from app.models.session import ScanSession
from app.core.exceptions import ExportError


class ReportExporter:
    @staticmethod
    def export_to_json(session: ScanSession, file_path: str) -> bool:
        try:
            data = session.to_dict()
            with open(file_path, "w", encoding="utf-8") as f:
                json.dump(data, f, indent=4, ensure_ascii=False)
            return True
        except Exception as e:
            raise ExportError(f"Failed to export JSON report: {e}")

    @staticmethod
    def export_to_csv(session: ScanSession, file_path: str) -> bool:
        try:
            with open(file_path, "w", newline="", encoding="utf-8") as f:
                writer = csv.writer(f)
                writer.writerow([
                    "IP Address",
                    "MAC Address",
                    "Hostname",
                    "Vendor",
                    "Detected OS",
                    "Response Time (ms)",
                    "Status",
                    "Open Ports Count",
                    "Open Ports Summary"
                ])
                for dev in session.devices:
                    ports_str = "; ".join([f"{p.port}/{p.protocol} ({p.service})" for p in dev.open_ports if p.state.lower() == "open"])
                    writer.writerow([
                        dev.ip,
                        dev.mac,
                        dev.hostname,
                        dev.vendor,
                        dev.os_detected,
                        f"{dev.response_time_ms:.2f}",
                        dev.status,
                        dev.open_port_count,
                        ports_str or "None"
                    ])
            return True
        except Exception as e:
            raise ExportError(f"Failed to export CSV report: {e}")

    @staticmethod
    def export_to_txt(session: ScanSession, file_path: str) -> bool:
        try:
            with open(file_path, "w", encoding="utf-8") as f:
                divider = "=" * 80
                subdivider = "-" * 80

                f.write(f"{divider}\n")
                f.write(" NETSENTINEL NETWORK SECURITY SCAN REPORT\n")
                f.write(f"{divider}\n")
                f.write(f" Scan Type     : {session.scan_type}\n")
                f.write(f" Target Range  : {session.target_range}\n")
                f.write(f" Started At    : {session.start_time}\n")
                f.write(f" Finished At   : {session.end_time or 'N/A'}\n")
                f.write(f" Duration      : {session.duration_seconds:.2f} seconds\n")
                f.write(f" Active Hosts  : {session.total_hosts_found}\n")
                f.write(f" Open Ports    : {session.total_open_ports}\n")
                f.write(f"{divider}\n\n")

                if not session.devices:
                    f.write(" No active hosts were detected during this scan.\n")
                else:
                    for idx, dev in enumerate(session.devices, 1):
                        f.write(f"[{idx}] Host: {dev.ip} ({dev.hostname})\n")
                        f.write(f"    MAC Address   : {dev.mac}\n")
                        f.write(f"    Vendor        : {dev.vendor}\n")
                        f.write(f"    OS Guess      : {dev.os_detected}\n")
                        f.write(f"    Latency       : {dev.response_time_ms:.2f} ms\n")
                        f.write(f"    Status        : {dev.status}\n")

                        if dev.open_ports:
                            f.write(f"    Open Ports ({len(dev.open_ports)}):\n")
                            f.write(f"      {'PORT':<10}{'PROTO':<8}{'STATE':<10}{'SERVICE':<18}{'BANNER'}\n")
                            f.write(f"      {'-'*70}\n")
                            for p in dev.open_ports:
                                banner_preview = (p.banner or "")[:35].replace("\r", "").replace("\n", " ")
                                f.write(f"      {p.port:<10}{p.protocol:<8}{p.state:<10}{p.service:<18}{banner_preview}\n")
                        else:
                            f.write("    Open Ports    : None detected / not scanned\n")

                        f.write(f"{subdivider}\n")

                f.write("\nReport generated by NetSentinel Scanner (XREFS0)\n")
            return True
        except Exception as e:
            raise ExportError(f"Failed to export TXT report: {e}")
